import { fromJS } from 'immutable';
import { storeName } from './selectors';

const initialState = fromJS({
  info:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Placerat duis ultricies lacus sed turpis tincidunt. Enim ut sem viverra aliquet eget sit. Turpis in eu mi bibendum neque egestas congue. Amet justo donec enim diam vulputate ut pharetra sit amet. Tellus pellentesque eu tincidunt tortor aliquam. Accumsan lacus vel facilisis volutpat est velit. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Magna etiam tempor orci eu lobortis elementum. Tortor condimentum lacinia quis vel eros donec. Massa massa ultricies mi quis hendrerit dolor magna eget. Et netus et malesuada fames ac turpis egestas sed tempus. Eu ultrices vitae auctor eu augue. In cursus turpis massa tincidunt dui. Malesuada bibendum arcu vitae elementum curabitur vitae nunc. Habitasse platea dictumst quisque sagittis purus sit amet. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Purus semper eget duis at tellus at urna condimentum mattis. Purus sit amet volutpat consequat mauris nunc. Duis ut diam quam nulla porttitor. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Nunc eget lorem dolor sed viverra ipsum. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Purus sit amet luctus venenatis lectus magna fringilla urna. Ipsum suspendisse ultrices gravida dictum fusce ut. Nam at lectus urna duis convallis convallis. Viverra mauris in aliquam sem fringilla. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Justo laoreet sit amet cursus sit amet dictum sit amet. Nulla at volutpat diam ut. Dictum varius duis at consectetur lorem donec massa sapien faucibus. Amet facilisis magna etiam tempor orci. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Augue interdum velit euismod in pellentesque massa placerat duis. Nec sagittis aliquam malesuada bibendum. Cras ornare arcu dui vivamus arcu felis bibendum. At lectus urna duis convallis. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Quam viverra orci sagittis eu volutpat. A iaculis at erat pellentesque. Non arcu risus quis varius quam quisque id diam vel. Ultrices eros in cursus turpis massa tincidunt dui. Volutpat odio facilisis mauris sit amet massa. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Aenean pharetra magna ac placerat vestibulum lectus mauris. Urna id volutpat lacus laoreet non curabitur. Convallis aenean et tortor at risus viverra.'
});

export default {
  [storeName]: function(state = initialState, action) {
    return state;
  }
};
