export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHANGE_ITEM_COUNT_CART = 'CHANGE_ITEM_COUNT_CART';
export const TOGGLE_CART = 'TOGGLE_CART';
