export const CHANGE_STREET_ADDRESS = 'CHANGE_STREET_ADDRESS';
export const CHANGE_PHONE_ADDRESS = 'CHANGE_PHONE_ADDRESS';
export const CHANGE_EMAIL_ADDRESS = 'CHANGE_EMAIL_ADDRESS';
export const CHANGE_NAME_ADDRESS = 'CHANGE_NAME_ADDRESS';
