export const GET_LIST_CITIES = 'GET_LIST_CITIES';
export const SET_LIST_CITIES = 'SET_LIST_CITIES';
export const RESET_LIST_CITIES = 'RESET_LIST_CITIES';
export const SELECT_CITY = 'SELECT_CITY';
export const REQUESTED_LIST_CITIES = 'REQUESTED_LIST_CITIES';
